version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  labels:
      - 'dependencies'
  commit-message:
      prefix: 'deps'
  ignore:
      - dependency-name: "pyvda*"
      - dependency-name: "wxpython*"
      - dependency-name: "regex*"
